services:
  backend:
    build: ../backend # Changed from ./backend
    ports:
      - "3000:3000"
    env_file:
      - ../backend/.env # Changed from ./backend/.env
    volumes:
      - ../backend/blog.db:/app/blog.db

  frontend:
    build: ../frontend # Changed from ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
